'use client';

import Login from '@/components/Login';
import { Button } from '@/components/ui/button';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import { useState } from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next AppXX',
//   description: 'Generated by create next app',
// };

function LayoutContent({
  children,
  isLoggedIn,
  onLogin,
}: {
  children: React.ReactNode;
  isLoggedIn: boolean;
  onLogin: () => void;
}) {
  if (!isLoggedIn) {
    return <Login onLogin={onLogin} />;
  }

  return (
    <>
      <div className='flex fixed justify-around w-full bg-slate-100'>
        <Button variant='link'>
          <Link href='/csr'>CSR</Link>
        </Button>
        <Button variant='link'>
          <Link href='/ssg'>SSG</Link>
        </Button>
        <Button variant='link'>
          <Link href='/ssr'>SSR</Link>
        </Button>
        <Button variant='link'>
          <Link href='/isr'>ISR</Link>
        </Button>
        <Button variant='link'>
          <Link href='/photos'>Photos</Link>
        </Button>
        <Button variant='link'>
          <Link href='/todos'>Todos</Link>
        </Button>
      </div>
      <div className='container mx-auto flex flex-col items-center justify-center pl-5 py-5'>
        <div className='mt-7'>{children}</div>
      </div>
    </>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  const handleLogin = () => {
    setIsLoggedIn(true);
  };

  return (
    <html lang='ko'>
      <body className={inter.className}>
        <LayoutContent isLoggedIn={isLoggedIn} onLogin={handleLogin}>
          {children}
        </LayoutContent>
      </body>
    </html>
  );
}
